version: "3"

services:
  minitrader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minitrader
    ports:
      - 8501:8501
    volumes:
      - ~/.minitrade:/root/.minitrade
